### ISSUE TITLE
Continuously show  'Installing application: bookinfo' and never success

### ISSUE THREAD

**Issue by cassie6** [nocalhost/nocalhost-vscode-plugin#124]
I install bookinfo application as your course, but it always ran with 'Installing application: bookinfo', and never success. I can't cancle the process and it don't fail, and don't tell me what's the matter. Just show 'Installing application: bookinfo'.
![image](https://user-images.githubusercontent.com/38715480/111901256-f453c400-8a71-11eb-8d5f-b861a7c52254.png)

**Comment by liangguangming** [comment]
You can switch to the output bar, and select Nocalhost, look at the output content.

**Comment by liangguangming** [comment]
Hi, did you solve the problem?
